### ISSUE TITLE
Select Competitions not leading to anything

### ISSUE THREAD

**Issue by timokvamme** [elParaguayo/service.bbclivefootballscores#37]
When I press Select Competitions, nothing is happening.

**Comment by elParaguayo** [comment]
Need to see a log file to help.

**Comment by timokvamme** [comment]
During a LeagueTable().getTable() call it throws an Attribute Error:  NoneType has no attribute 'find'

**Comment by elParaguayo** [comment]
Are you using latest version? BBC changed their site at the start of the season so the code had to be re-written. At the moment you can't select competitions, only teams.

Release is here: https://github.com/elParaguayo/service.bbclivefootballscores/releases/tag/0.5.0

**Comment by timokvamme** [comment]
I switched away from that because it wasn't working either.
when I have selected a team, (its in yellow). and i press OK. nothing happens 
http://prntscr.com/i3kaiz 
It just exits and im back to this: http://prntscr.com/i3kc3l 
Tried several teams.

No event in log, reproduced on both Win10 and Android.

**Comment by elParaguayo** [comment]
The old version won't work so switching back is no good.

I don't see a problem with either screenshot. Are Aberdeen playing today? If not, nothing is going to happen?

**Comment by timokvamme** [comment]
I thought the addon would be able to show league standings?, - how do i access those?. 
is it intended that one is not able to press run? 
http://prntscr.com/i3khek 
Sorry i've ive completely missed the point of this addon.

**Comment by elParaguayo** [comment]
That was available in old version. It's not available at the moment. Addon just does what it was originally designed to do: show notifications during live matches.

**Comment by elParaguayo** [comment]
If I get time to rewrite the code to do the old bits I will but it's taken 6 months to do the notifications so I wouldn't hold your breath!

**Comment by timokvamme** [comment]
ah ok :D, you know of any addon that can show league standings?. 
I've tried matchcenter but it shows the standings from 2016/2017

**Comment by elParaguayo** [comment]
Matchcenter would be your best bet I think.
